apiVersion: networking.k8s.io/v1
kind: Ingress	
metadata:	
  name: task-management	
  annotations:	
    kubernetes.io/ingress.class: "nginx"	
    ingress.kubernetes.io/ssl-redirect: "false"	
    nginx.ingress.kubernetes.io/ssl-redirect: "false"	
spec:	
  rules:	
  - http:	
      paths:	
      - path: /task-management-api
        pathType: ImplementationSpecific
        backend:	
          service:
            name: task-management-api
            port:
              number: 8080

---	

apiVersion: apps/v1
kind: Deployment	
metadata:	
  name: task-management-db
spec:	
  selector:	
    matchLabels:	
      type: db	
      service: task-management	
  strategy:	
    type: Recreate	
  template:	
    metadata:	
      labels:	
        type: db	
        service: task-management	
        vendor: Postgres	
    spec:	
      containers:	
      - name: db	
        image: postgres:10.1
        env:	
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
             configMapKeyRef:
              name: postgres-configmap
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: postgres-db

---	

apiVersion: v1	
kind: Service	
metadata:	
  name: task-management-db
spec:	
  ports:	
  - port: 5432
  selector:	
    type: db
    service: task-management

---	

apiVersion: apps/v1
kind: Deployment	
metadata:	
  name: task-management-api	
spec:	
  replicas: 3	
  selector:	
    matchLabels:	
      type: api	
      service: task-management	
  template:	
    metadata:	
      labels:	
        type: api	
        service: task-management	
        language: node	
    spec:	
      containers:	
      - name: api	
        image: task-management-api
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: db-port
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: db-password
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: db-database
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: port
        - name: STAGE
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: stage
        - name: PREFIX
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: prefix
        livenessProbe:	
          httpGet:	
            path: /task-management-api/health	
            port: 8080
          periodSeconds: 3	
        readinessProbe:
          httpGet:
            path: /task-management-api/health	
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3	
---	

apiVersion: v1	
kind: Service	
metadata:	
  name: task-management-api
spec:
  ports:	
  - port: 8080
  selector:	
    type: api
    service: task-management



---

apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-configmap
data:
    postgres-db: task-management
    postgres-user: postgres
    postgres-password: postgres

---

apiVersion: v1
kind: ConfigMap
metadata:
    name: api-configmap
data:
    db-host: task-management-db
    db-port: "5432"
    db-database: task-management
    db-username: postgres
    db-password: postgres
    stage: dev
    port: "8080"
    prefix: "task-management-api"
