apiVersion: networking.k8s.io/v1
kind: Ingress	
metadata:	
  name: task-management	
  annotations:	
    kubernetes.io/ingress.class: "nginx"	
    ingress.kubernetes.io/ssl-redirect: "false"	
    nginx.ingress.kubernetes.io/ssl-redirect: "false"	
spec:	
  rules:	
  - http:	
      paths:	
      - path: /task-management
        pathType: ImplementationSpecific
        backend:	
          service:
            name: task-management-api
            port:
              number: 8080

---	

apiVersion: apps/v1
kind: Deployment	
metadata:	
  name: task-management-db
spec:	
  selector:	
    matchLabels:	
      type: db	
      service: task-management	
  strategy:	
    type: Recreate	
  template:	
    metadata:	
      labels:	
        type: db	
        service: task-management	
        vendor: Postgres	
    spec:	
      containers:	
      - name: db	
        image: postgres:10.1
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
             configMapKeyRef:
              name: postgres-configmap
              key: postgres-password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: postgres-host
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: postgres-db
        resources:	
          limits:	
            memory: "100Mi"	
            cpu: 0.1	
          requests:	
            memory: "50Mi"	
            cpu: 0.01	

---	

apiVersion: v1	
kind: Service	
metadata:	
  name: task-management-db	
spec:	
  ports:	
  - port: 5432
  selector:	
    type: db
    app: postgres	
    service: task-management

---	

apiVersion: apps/v1
kind: Deployment	
metadata:	
  name: task-management-api	
spec:	
  replicas: 3	
  selector:	
    matchLabels:	
      type: api	
      service: task-management	
  template:	
    metadata:	
      labels:	
        type: api	
        service: task-management	
        language: node	
    spec:	
      containers:	
      - name: api	
        image: task-management-api
        env:	
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: db-port
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: db-password
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: db-database
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: port
        - name: STAGE
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: stage
       
        resources:	
          limits:	
            memory: "25Mi"	
            cpu: 0.1	
          requests:	
            memory: "5Mi"	
            cpu: 0.01	

---	

apiVersion: v1	
kind: Service	
metadata:	
  name: task-management-api	
spec:	
  ports:	
  - port: 8080
  selector:	
    type: api
    app: node	
    service: task-management


---

apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-configmap
data:
    postgres-host: postgres-service
    postgres-db: task-management
    postgres-user: postgres
    postgres-password: postgres

---

apiVersion: v1
kind: ConfigMap
metadata:
    name: api-configmap
data:
    db-host: postgres-service
    db-port: "5432"
    db-database: task-management
    db-username: postgres
    db-password: postgres
    stage: dev
    port: "8080"
