apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: task-management-api
build:
  artifacts:
  - image: task-management-api
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-pod.yaml
